# 容器 配置
server:
  port: 80
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

# 数据库 及 Redis 配置    
spring:
  redis:
    host: [host]
    port: [端口号]
    password: [密码]
  datasource:
    url: jdbc:mysql://[host]:3306/ictgu?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: [账号]
    password: [密码]
    sql-script-encoding: utf-8
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 10
  mail:
    host: smtp.ym.163.com[此处填你的邮箱服务地址]
    username: [账号]
    password: [密码]
    properties:
      mail:
        smtp:
          auth: false
        starttls:
          enable: false
          required: false

# Mybatis 配置
mybatis:
  config-location: classpath:/mybatis.xml

# Redis Key 前缀
redis:
  prefix:
    signUp: SIGN

# 本站信息
app:
  name: 沧海云
  domain: ictgu.cn
